"""remove full_name from users

Revision ID: 26853686759a
Revises: add_multi_user_fields_only
Create Date: 2025-07-21 12:14:56.015895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26853686759a'
down_revision: Union[str, Sequence[str], None] = 'add_multi_user_fields_only'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
