"""initial_improved_schema

Revision ID: 2cbc8991cbce
Revises: 
Create Date: 2025-07-15 02:07:13.613793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cbc8991cbce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates_new')
    op.drop_table('sandbox_metrics_new')
    op.drop_table('sandboxes_new')
    op.drop_table('projects_new')
    op.drop_table('sandbox_usage_new')
    op.drop_table('api_keys_new')
    op.drop_table('notifications_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications_new',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('related_entity_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('related_entity_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('api_keys_new',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('key_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('full_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('permissions', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('expires_in_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_used_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sandbox_usage_new',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('sandbox_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('running_seconds', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cpu_hours', mysql.FLOAT(), nullable=True),
    sa.Column('memory_hours', mysql.FLOAT(), nullable=True),
    sa.Column('storage_hours', mysql.FLOAT(), nullable=True),
    sa.Column('hourly_rate', mysql.FLOAT(), nullable=False),
    sa.Column('cost', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projects_new',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('owner_id', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sandboxes_new',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('template_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('owner_id', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('project_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('cpu_spec', mysql.FLOAT(), nullable=False),
    sa.Column('memory_spec', mysql.FLOAT(), nullable=False),
    sa.Column('max_running_seconds', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('region', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('visibility', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('started_at', mysql.DATETIME(), nullable=True),
    sa.Column('stopped_at', mysql.DATETIME(), nullable=True),
    sa.Column('timeout_at', mysql.DATETIME(), nullable=True),
    sa.Column('recycled_at', mysql.DATETIME(), nullable=True),
    sa.Column('latest_snapshot_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('snapshot_expires_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sandbox_metrics_new',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('sandbox_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('cpu_utilization', mysql.FLOAT(), nullable=True),
    sa.Column('memory_utilization', mysql.FLOAT(), nullable=True),
    sa.Column('storage_utilization', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('templates_new',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('min_cpu_required', mysql.FLOAT(), nullable=False),
    sa.Column('min_memory_required', mysql.FLOAT(), nullable=False),
    sa.Column('is_official', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('owner_id', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('repository_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('tags', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
