"""fix switch project endpoint to use JSON body

Revision ID: 7dd8ebd2a37b
Revises: b88f5dd49ea2
Create Date: 2025-07-17 05:00:49.180571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd8ebd2a37b'
down_revision: Union[str, Sequence[str], None] = 'b88f5dd49ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
