"""Add pending_signups table

Revision ID: 87bb50aeea65
Revises: be0612073e71
Create Date: 2025-07-09 15:03:20.230093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bb50aeea65'
down_revision: Union[str, Sequence[str], None] = 'be0612073e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('verification_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_signups_email'), 'pending_signups', ['email'], unique=True)
    op.create_index(op.f('ix_pending_signups_id'), 'pending_signups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_signups_id'), table_name='pending_signups')
    op.drop_index(op.f('ix_pending_signups_email'), table_name='pending_signups')
    op.drop_table('pending_signups')
    # ### end Alembic commands ###
