"""add account email change table

Revision ID: b14291101d4b
Revises: 26853686759a
Create Date: 2025-07-21 12:46:24.213393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b14291101d4b'
down_revision: Union[str, Sequence[str], None] = '26853686759a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_email_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.String(length=25), nullable=False),
    sa.Column('account_id', sa.String(length=12), nullable=False),
    sa.Column('current_email', sa.String(length=255), nullable=False),
    sa.Column('new_email', sa.String(length=255), nullable=False),
    sa.Column('current_email_token', sa.String(length=255), nullable=False),
    sa.Column('new_email_token', sa.String(length=255), nullable=False),
    sa.Column('current_email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('new_email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_id')
    )
    op.create_index(op.f('ix_account_email_changes_change_id'), 'account_email_changes', ['change_id'], unique=True)
    op.create_index(op.f('ix_account_email_changes_current_email_token'), 'account_email_changes', ['current_email_token'], unique=False)
    op.create_index(op.f('ix_account_email_changes_new_email_token'), 'account_email_changes', ['new_email_token'], unique=False)
    op.create_index(op.f('ix_account_email_changes_account_id'), 'account_email_changes', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_email_changes_expires_at'), 'account_email_changes', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_email_changes_expires_at'), table_name='account_email_changes')
    op.drop_index(op.f('ix_account_email_changes_account_id'), table_name='account_email_changes')
    op.drop_index(op.f('ix_account_email_changes_new_email_token'), table_name='account_email_changes')
    op.drop_index(op.f('ix_account_email_changes_current_email_token'), table_name='account_email_changes')
    op.drop_index(op.f('ix_account_email_changes_change_id'), table_name='account_email_changes')
    op.drop_table('account_email_changes')
    # ### end Alembic commands ###
