"""Drop region and visibility columns from sandboxes, make project_id NOT NULL

Revision ID: b88f5dd49ea2
Revises: 666ed0fbe879
Create Date: 2025-07-17 03:06:53.464413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88f5dd49ea2'
down_revision: Union[str, Sequence[str], None] = '666ed0fbe879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
