"""add_sandbox_specifications

Revision ID: c43f335d9ef6
Revises: add_api_keys_table
Create Date: 2025-07-14 08:33:19.823641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c43f335d9ef6'
down_revision: Union[str, Sequence[str], None] = 'add_api_keys_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_ibfk_1'), 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_sandbox_metrics_sandbox_id'), table_name='sandbox_metrics')
    op.drop_index(op.f('ix_sandbox_metrics_timestamp'), table_name='sandbox_metrics')
    op.drop_column('sandbox_metrics', 'bandwidth_usage')
    op.add_column('sandbox_usage', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('sandbox_usage', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('sandbox_usage', sa.Column('cpu_hours', sa.Float(), nullable=True))
    op.add_column('sandbox_usage', sa.Column('memory_hours', sa.Float(), nullable=True))
    op.add_column('sandbox_usage', sa.Column('storage_hours', sa.Float(), nullable=True))
    op.add_column('sandbox_usage', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('sandbox_usage', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('sandbox_usage', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_sandbox_usage_id'), table_name='sandbox_usage')
    op.drop_index(op.f('ix_sandbox_usage_sandbox_id'), table_name='sandbox_usage')
    op.drop_index(op.f('ix_sandbox_usage_timestamp'), table_name='sandbox_usage')
    op.create_foreign_key(None, 'sandbox_usage', 'users', ['user_id'], ['account_id'])
    op.drop_column('sandbox_usage', 'memory_usage')
    op.drop_column('sandbox_usage', 'timestamp')
    op.drop_column('sandbox_usage', 'bandwidth_usage')
    op.drop_column('sandbox_usage', 'cost_increment')
    op.drop_column('sandbox_usage', 'storage_usage')
    op.drop_column('sandbox_usage', 'cpu_usage')
    op.add_column('sandboxes', sa.Column('cpu_requirements', sa.Float(), nullable=True))
    op.add_column('sandboxes', sa.Column('memory_requirements', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_sandboxes_created_at'), table_name='sandboxes')
    op.drop_index(op.f('idx_sandboxes_framework_status'), table_name='sandboxes')
    op.drop_index(op.f('idx_sandboxes_user_status'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_framework'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_name'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_project_id'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_region'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_status'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_visibility'), table_name='sandboxes')
    op.create_index('ix_sandboxes_created_at', 'sandboxes', ['created_at'], unique=False)
    op.alter_column('templates', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('templates', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_constraint(op.f('templates_ibfk_1'), 'templates', type_='foreignkey')
    op.create_foreign_key(None, 'templates', 'users', ['owner_id'], ['id'])
    op.alter_column('users', 'account_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'account_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint('templates_ibfk_1', 'templates', type_='foreignkey')
    op.create_foreign_key(op.f('templates_ibfk_1'), 'templates', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('templates', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('templates', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index('ix_sandboxes_created_at', table_name='sandboxes')
    op.create_index(op.f('ix_sandboxes_visibility'), 'sandboxes', ['visibility'], unique=False)
    op.create_index(op.f('ix_sandboxes_status'), 'sandboxes', ['status'], unique=False)
    op.create_index(op.f('ix_sandboxes_region'), 'sandboxes', ['region'], unique=False)
    op.create_index(op.f('ix_sandboxes_project_id'), 'sandboxes', ['project_id'], unique=False)
    op.create_index(op.f('ix_sandboxes_name'), 'sandboxes', ['name'], unique=False)
    op.create_index(op.f('ix_sandboxes_framework'), 'sandboxes', ['framework'], unique=False)
    op.create_index(op.f('idx_sandboxes_user_status'), 'sandboxes', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_sandboxes_framework_status'), 'sandboxes', ['framework', 'status'], unique=False)
    op.create_index(op.f('idx_sandboxes_created_at'), 'sandboxes', ['created_at'], unique=False)
    op.drop_column('sandboxes', 'memory_requirements')
    op.drop_column('sandboxes', 'cpu_requirements')
    op.add_column('sandbox_usage', sa.Column('cpu_usage', mysql.FLOAT(), nullable=False))
    op.add_column('sandbox_usage', sa.Column('storage_usage', mysql.FLOAT(), nullable=False))
    op.add_column('sandbox_usage', sa.Column('cost_increment', mysql.FLOAT(), nullable=False))
    op.add_column('sandbox_usage', sa.Column('bandwidth_usage', mysql.FLOAT(), nullable=False))
    op.add_column('sandbox_usage', sa.Column('timestamp', mysql.DATETIME(), nullable=False))
    op.add_column('sandbox_usage', sa.Column('memory_usage', mysql.FLOAT(), nullable=False))
    op.drop_constraint('sandbox_usage_ibfk_1', 'sandbox_usage', type_='foreignkey')
    op.create_index(op.f('ix_sandbox_usage_timestamp'), 'sandbox_usage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sandbox_usage_sandbox_id'), 'sandbox_usage', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_sandbox_usage_id'), 'sandbox_usage', ['id'], unique=False)
    op.alter_column('sandbox_usage', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_column('sandbox_usage', 'created_at')
    op.drop_column('sandbox_usage', 'cost')
    op.drop_column('sandbox_usage', 'storage_hours')
    op.drop_column('sandbox_usage', 'memory_hours')
    op.drop_column('sandbox_usage', 'cpu_hours')
    op.drop_column('sandbox_usage', 'date')
    op.drop_column('sandbox_usage', 'user_id')
    op.add_column('sandbox_metrics', sa.Column('bandwidth_usage', mysql.FLOAT(), nullable=False))
    op.create_index(op.f('ix_sandbox_metrics_timestamp'), 'sandbox_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sandbox_metrics_sandbox_id'), 'sandbox_metrics', ['sandbox_id'], unique=False)
    op.create_foreign_key(op.f('notifications_ibfk_1'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
