"""add last_password_reset_request column

Revision ID: c94a5d74a48e
Revises: ce54d03dff09
Create Date: 2025-07-10 02:43:15.493200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94a5d74a48e'
down_revision: Union[str, Sequence[str], None] = 'ce54d03dff09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_password_reset_request', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_reset_request')
    # ### end Alembic commands ###
