"""add full_key column to api_keys

Revision ID: cd6417fa58ca
Revises: 3eaea20db75d
Create Date: 2025-07-10 08:26:46.216211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd6417fa58ca'
down_revision: Union[str, Sequence[str], None] = '3eaea20db75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_usage_id'), table_name='api_key_usage')
    op.drop_table('api_key_usage')
    op.drop_index(op.f('ix_api_rate_limits_id'), table_name='api_rate_limits')
    op.drop_table('api_rate_limits')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    op.drop_index(op.f('uq_userid_apikeyname'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('key_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('key_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('prefix', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('permissions', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('expires_in_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_used_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_userid_apikeyname'), 'api_keys', ['user_id', 'name'], unique=True)
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('api_rate_limits',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('api_key_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('window_start', mysql.DATETIME(), nullable=False),
    sa.Column('request_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_api_rate_limits_id'), 'api_rate_limits', ['id'], unique=False)
    op.create_table('api_key_usage',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('api_key_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('endpoint', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('method', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('status_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', mysql.TEXT(), nullable=True),
    sa.Column('request_size_bytes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('response_size_bytes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_api_key_usage_id'), 'api_key_usage', ['id'], unique=False)
    # ### end Alembic commands ###
